### ISSUE TITLE
Tracking issue: business day logic

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#11568]
This comes up sometimes, e.g.
- https://www.reddit.com/r/datascience/comments/16eiddh/comment/jzxpg81/?utm_source=share&utm_medium=web2x&context=3
- https://github.com/pola-rs/polars/issues/2420
- https://github.com/pola-rs/polars/issues/5713
- https://github.com/pola-rs/polars/issues/9779
- https://discord.com/channels/908022250106667068/911186243465904178/1101834949016952832
- https://discord.com/channels/908022250106667068/911186243465904178/1119680657946329229
- https://discord.com/channels/908022250106667068/911186243465904178/1130547750342242475

What should be done about this, what should the API be?

I'd suggest adding `"bd"` to the string language, and then methods which accept the string language can also take an extra `business_day_options` argument. So, for example, to generate a range of dates in 2023 where Wednesday and Sunday are holidays, and the only public holiday is say 2023-12-25, then they could do:
```python
business_day_options = {
    'holidays': [date(2023, 12, 15)],
    'weekday_mask': ['Mon Tue Thu Fri Sat'],
}
pl.date_range(date(2023, 1, 1), date(2024, 1, 1), '1bd', closed='left', business_day_options=business_day_options, eager=True)
```
Users could pass the holidays from the Python `holidays` package if they wish (this could be documented)

Tackling this could be done in stages:
- [ ] add `'bd'` to the string language. This would be just like 'd', but would skip weekends. This should be fairly simple, and might even be doable without the [bdays](https://docs.rs/bdays/latest/bdays/) crate
- [ ] add `business_day_options` argument to functions which accept duration strings
- [ ] add `'bmo'`, `'bh'`, and so on...
- [ ] consider: should the duration string language allow a prefix `business_`, and then everything after is considered business-aware? like `interval='business_1mo2d'` rather than `'1bmo1bd'`

**Comment by JulianCologne** [comment]
I would love to see business day logic in polars!

However, one question regarding the API desing:
Why are many temporal functions using this "string language" (3d12h4m25s: 3 days, 12 hours, 4 minutes, and 25 seconds)?

I think it would be more pythonic, easier to read, easiert to parse(?) and easier to type checkers to use individual arguments like in pythons datetime/timedelta
- `datetime(year=2023, month=1, day=2, hour=3)`
- `timedelta(weeks=1, days=1, seconds=2, milliseconds=3, microseconds=4)`

So instead of
```python
pl.some_temporal_func(interval='business_1mo2d_saturating')
pl.some_temporal_func(interval='1bmo2bd_saturating')
```
you would write
```python
pl.some_temporal_func(
    months=1,
    days=2,
    saturating=True,
    business=True,
)
```

**Comment by MarcoGorelli** [comment]
Thanks for your suggestion, could you open a separate issue about that please? I think it could be done originally to business day logic

**Comment by orlp** [comment]
I'm not a huge fan of adding a specific business day logic. Could this not be handled by putting a normal filter on `.dt.weekday` after the `date_range`?

**Comment by MarcoGorelli** [comment]
for `date_range` specifically, then yes

an example of when it's less trivial is `ser.dt.offset_by('5bd')`

converting to numpy and using `np.busday_offset` does work, but it breaks lazy execution

**Comment by MarcoGorelli** [comment]
Just to have a quick example: I _could_ achieve the above by using `date_ranges` to create a long enough date range, then filtering out weekends, and finally take the nth element

But, from a quick test, this would be slower than converting to numpy by a factor of about 100 (and that's on just 50,000 rows!)

```python
In [1]: df = pl.DataFrame({
   ...:     'ts': pl.date_range(date(1900, 1, 1), date(2100, 1, 1), eager=True)
   ...: })

In [2]: df = df.filter(pl.col('ts').dt.weekday() < 6)

In [3]: def offset_by_n_bd(col_name, n):
   ...:     return (
   ...:         pl.date_ranges(
   ...:             pl.col(col_name), pl.col(col_name).dt.offset_by(f"{2*n}d")
   ...:         )
   ...:         .list.eval(pl.element().filter(pl.element().dt.weekday() < 6))
   ...:         .list.get(n)
   ...:     )
   ...:

In [4]: %time df.with_columns(offset_by_n_bd('ts', 5))
CPU times: user 144 ms, sys: 25.8 ms, total: 169 ms
Wall time: 127 ms
Out[4]:
shape: (52_180, 2)
┌────────────┬────────────┐
│ ts         ┆ date_range │
│ ---        ┆ ---        │
│ date       ┆ date       │
╞════════════╪════════════╡
│ 1900-01-01 ┆ 1900-01-08 │
│ 1900-01-02 ┆ 1900-01-09 │
│ 1900-01-03 ┆ 1900-01-10 │
│ 1900-01-04 ┆ 1900-01-11 │
│ …          ┆ …          │
│ 2099-12-29 ┆ 2100-01-05 │
│ 2099-12-30 ┆ 2100-01-06 │
│ 2099-12-31 ┆ 2100-01-07 │
│ 2100-01-01 ┆ 2100-01-08 │
└────────────┴────────────┘

In [5]: %time df.with_columns(ts_plus_5bd=pl.Series(np.busday_offset(df['ts'], 5)))
CPU times: user 5.33 ms, sys: 0 ns, total: 5.33 ms
Wall time: 8.92 ms
Out[5]:
shape: (52_180, 2)
┌────────────┬─────────────┐
│ ts         ┆ ts_plus_5bd │
│ ---        ┆ ---         │
│ date       ┆ date        │
╞════════════╪═════════════╡
│ 1900-01-01 ┆ 1900-01-08  │
│ 1900-01-02 ┆ 1900-01-09  │
│ 1900-01-03 ┆ 1900-01-10  │
│ 1900-01-04 ┆ 1900-01-11  │
│ …          ┆ …           │
│ 2099-12-29 ┆ 2100-01-05  │
│ 2099-12-30 ┆ 2100-01-06  │
│ 2099-12-31 ┆ 2100-01-07  │
│ 2100-01-01 ┆ 2100-01-08  │
└────────────┴─────────────┘
```

**Comment by ritchie46** [comment]
Do we need this included in the string language or as expressions? If it is only expressions, it is a perfect fit for the new polars plugins. Then we could have a separate python package with business days expressions.

**Comment by MarcoGorelli** [comment]
hmm yeah maybe the separate package would be `.bdt` instead of `.dt`, and that could support some business-day-related features

I'll give this a try then! I need to learn the plugins anyway

**Comment by ion-elgreco** [comment]
> I'm not a huge fan of adding a specific business day logic. Could this not be handled by putting a filter on `.dt.weekday()` after the `date_range`?

This becomes quite difficult quickly when you want to this on hour level. Suppose, I need to create hours for the 3 factory shift.  With Pandas you can create custom business hours start and stop. In Polars I would have to create the range first, then filter out certain weekdays, holidays and breaks between the shifts.

```python
import pandas as pd
freq = pd.offsets.CustomBusinessHour(n=1, start=["08:00",  "13:30", "19:00"], end=["13:00","18:30", "01:00"])

dates = pd.bdate_range(dt.datetime(2000, 1, 1), dt.datetime(2023, 1, 1), freq=freq).to_series()

0    2000-01-01 00:00:00
1    2000-01-03 08:00:00
2    2000-01-03 09:00:00
3    2000-01-03 10:00:00
4    2000-01-03 11:00:00
5    2000-01-03 12:00:00
6    2000-01-03 13:30:00
7    2000-01-03 14:30:00
8    2000-01-03 15:30:00
9    2000-01-03 16:30:00
10   2000-01-03 17:30:00
11   2000-01-03 19:00:00
12   2000-01-03 20:00:00
13   2000-01-03 21:00:00
14   2000-01-03 22:00:00
15   2000-01-03 23:00:00
16   2000-01-04 00:00:00
17   2000-01-04 08:00:00
18   2000-01-04 09:00:00
19   2000-01-04 10:00:00
dtype: datetime64[ns]

```

**Comment by orlp** [comment]
If it weren't for the pesky 24th hour this could use `time_ranges`.

```python
from datetime import datetime, timedelta, time
workhours = pl.DataFrame({"hour": [
  timedelta(hours=h, minutes=m)
  for (h, m) in
  [(8, 0), (9, 0), (10, 0), (11, 0), (12, 0),
   (13, 30), (14, 30), (15, 30), (16, 30), (17, 30),
   (19, 0), (20, 0), (21, 0), (22, 0), (23, 0), (24, 0)]
]})
dates = pl.select(pl.datetime_range(datetime(2000, 1, 1), datetime(2023, 1, 1)))
workdays = dates.select(pl.col("datetime").filter(pl.col("datetime").dt.weekday() <= 5))
df = workdays.join(workhours, how="cross").select(pl.col("datetime") + pl.col("hour"))

```

**Comment by MarcoGorelli** [comment]
Taken forwards in https://github.com/MarcoGorelli/polars-business , closing then

**Comment by ion-elgreco** [comment]
Great work @MarcoGorelli!
