### ISSUE TITLE
Expression IR todo log.

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#15161]
Just for me to keep a checklist.

- [ ] rewrite `det_join_schema` in terms of `ExprIR`.
- [ ] resolve wildcard in `AExpr`.
- [ ] rewrite `rename_matching_aexpr_leaf_names` (use this in join where we mutate expression)

**Comment by coastalwhite** [comment]
Guessing this is stale.
