### ISSUE TITLE
Tracking Issue: Utilizing and Keeping track of Metadata

### ISSUE THREAD

**Issue by coastalwhite** [pola-rs/polars#17070]
This issue tracks all the oppertunities to use and keep track of different types of metadata. This metadata is now kept on `ChunkedArray` and can be retrieved from a `Series` with the `SeriesTrait::get_metadata`. The plan is to initially add a lot of functionally between the `MetadataEnv::experimental_enabled` (which can be enabled with `POLARS_METADATA_USE=experimental`, but to later make this enabled by default.

List of metadata fields that can be included:

- [ ] `parted`: All duplicates are clustered together (e.g. `[1, 1, 1, 0, 0, 3, 2, 2]`)

List of operations where metadata can be used or set:

- [ ] `expand_from_offset` can set the `distinct_count` to `1`
- [ ] A `distinct_count=1` can immediatly make a group slice as one group
- [ ] A `group_by` can set the `distinct_count` per key

**Comment by deanm0000** [comment]
Is this one similar to enabling extension arrays? That would be amazing of extension arrays followed this.

Back to this one, are you going to have meta data stored in parquet, loosely like this maybe https://stackoverflow.com/a/77642404/1818713?

**Comment by deanm0000** [comment]
Link to extension type request https://github.com/pola-rs/polars/issues/9112

**Comment by coastalwhite** [comment]
> Is this one similar to enabling extension arrays? That would be amazing of extension arrays followed this.
> 
> Back to this one, are you going to have meta data stored in parquet, loosely like this maybe https://stackoverflow.com/a/77642404/1818713?

That is not really the focus of this effort. This effort is really to utilize and track metadata or statistics internally that can speed up computations. E.g. if we know the minimum value already, doing a `min` can be free. We already track various kinds of metadata (sorting, null_count, fast_explode), but we would like to track a lot more and effectively utilize that information.

**Comment by alippai** [comment]
Arrow should allow read & write of statistics via IPC: https://arrow.apache.org/docs/format/StatisticsSchema.html#standard-statistics

**Comment by coastalwhite** [comment]
I think this is a bit stale, as this refers to the runtime statistics
