### ISSUE TITLE
Tracking issue for improvements to `polars-row`

### ISSUE THREAD

**Issue by coastalwhite** [pola-rs/polars#19903]
The `polars-row` subcrate provides the [row-encoding] is used by Polars. It is now in a very bare state and should be improved to provide better possibilities in sorting, joins and the new streaming engine.

Here is a list of improvements that I would like to look into:
- [x] Fully implement nested encoding / decoding (#19874)
- [x] Improve `pl.List` encoding with continuation tokens instead of variable length encoding. This allows empty child encoding, removes the need for an intermediate buffer, and massively reduces the amount of space needed by the row encoding. I do need to verify that it fully works :sweat_smile:. (#19907)
- [x] ~Properly implement `Dictionary` encoding (to be used by `pl.Enum` and `pl.Categorical`), using the method described by the [`arrow-row`] people. We need to investigate how to roundtrip this efficiently (e.g. with a bidirectional `HashMap`).~ We implemented our own encoding that does not rely on the tricks discovered by the arrow people.
- [ ] Implement optimizations for `BinaryView` to be similar to `Dictionary` when the cardinality of views is low. We need to find a way to estimate this cardinality. It might also be worth it to consider the average length of a view. This is for instance probably not really worth it if all views are inlinable anyway.
- [x] Implement optimizations for strings to not use the variable encoding but use properties of UTF-8 instead. (#19911)
- [ ] Implement an optimization for `Column` encoding so that `ScalarColumn` and `PartedColumn` encoding becomes much cheaper.
- [x] Reduce the size of `Boolean` to at most one byte. (#19927)
- [ ] Introduce 2 loop systems for validity. Remove quadratic reserve!
- [ ] Look into variable-length encoding for integers (#19929).

[row-encoding]: https://arrow.apache.org/blog/2022/11/07/multi-column-sorts-in-arrow-rust-part-1/
[`arrow-row`]: https://arrow.apache.org/rust/arrow_row/index.html
