### ISSUE TITLE
python 0.17.x 

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/polars#7815]
A list of breaking changes that have to be merged:

- [x] unique: default to `maintain_order=False`. Current state blocks streaming
- [x] shift_and_fill: #7192
- [x] [toggle_string_cache](https://github.com/pola-rs/polars/issues/7815#issuecomment-1485467578)
- [x] [error names](https://github.com/pola-rs/polars/issues/7815#issuecomment-1485494673)
- [x] pivot column names: https://github.com/pola-rs/polars/issues/7731#issuecomment-1487237635
- [x] `top_k(descending)` to `bottom_k`

I hope we can release 7 April, so hit us with gripes you want to see fixed. ;)

**Comment by alexander-beedie** [comment]
Ah, I have one: `toggle_string_cache` should be renamed `enable_string_cache` (or `activate_string_cache`?)

* _"Toggle"_ means to flip the state from whatever it is now to its opposite (eg: `on → off → on → off`).
* However... our function _doesn't_ toggle - it specifically enables or disables the cache based on the provided boolean.

**Comment by ghuls** [comment]
This didn't make it last breaking release, but should be include this time:

chore(python): Rename all Polars specifc exceptions to *Error as recommended by PEP8: https://github.com/pola-rs/polars/pull/6009

```diff
   NoDataError
-   NoRowsReturned
-   PanicException
-   RowsException
+   NoRowsReturnedError
+   PolarsPanicError
+  RowsError
    SchemaError
    SchemaFieldNotFoundError
    ShapeError
    StructFieldNotFoundError
-   TooManyRowsReturned
+   TooManyRowsReturnedError
```

**Comment by ghuls** [comment]
There are some of @stinodego pull request that have the breaking label:
https://github.com/pola-rs/polars/pulls?q=is%3Apr+is%3Aopen+label%3Abreaking+

**Comment by stinodego** [comment]
I assigned a bunch of stuff to the 0.17.0 milestone:
https://github.com/pola-rs/polars/milestone/3

Can we start merging breaking stuff already, or do you want to do another release before then? Because then I'll start rebasing 😎

**Comment by s-banach** [comment]
This is nothing to do with the API, but I hope #6513  can be fixed before the next major release.
IMO, broken sort for one of the dtypes should be treated like a serious issue.

**Comment by ritchie46** [comment]
> This is nothing to do with the API, but I hope #6513 can be fixed before the next major release. IMO, broken sort for one of the dtypes should be treated like a serious issue.

Please post on that issue and keep this one one topic.

**Comment by MarcoGorelli** [comment]
Could the `pivot` change suggested in https://github.com/pola-rs/polars/issues/7731#issuecomment-1487237635 be a candidate for a breaking change in 0.17?

**Comment by ritchie46** [comment]
> Could the `pivot` change suggested in [#7731 (comment)](https://github.com/pola-rs/polars/issues/7731#issuecomment-1487237635) be a candidate for a breaking change in 0.17?

Yes! The duplicates must be fixed rather sooner than later.

**Comment by ghuls** [comment]
Slightly in relation to:
https://github.com/pola-rs/polars/pull/7983

It might be good idea to rename `to_series` to `get_series` as with `to_series` somehow I would expect that I would get a list of all series for the whole dataframe by default (what `df.get_columns()` is actually doing).

In my opinion it would be more logical that:
`df.to_series()` ==> return dataframe as list of series (current `df.get_columns()` implementation.
`df.get_column()` ==> get column from dataframe as a series and support it with `int` and `str` values (so combine current get_colum and to_series).

**Comment by StevenLi-DS** [comment]
@ghuls Change `drop_nulls` to `drop_null`? It is the only plural `nulls` among all method that deals with nulls...
