### ISSUE TITLE
Tracker: offset-aware parsing

### ISSUE THREAD

**Issue by MarcoGorelli** [pola-rs/polars#8860]
The general suggestion is that, when parsing date time strings, then offsets such as `'+01:00'` should be converted to UTC, and that `UTC` should be the time zone.

### 1. Parsing strings

Current behaviour:
```python
In [27]: pl.Series(['2020-01-01T01:00+01:00']).str.to_datetime()
Out[27]:
shape: (1,)
Series: '' [datetime[μs, +01:00]]
[
        2020-01-01 01:00:00 +01:00
]
```
Future behaviour:
```python
In [28]: pl.Series(['2020-01-01T01:00+01:00']).str.to_datetime()
Out[28]:
shape: (1,)
Series: '' [datetime[μs, UTC]]
[
        2020-01-01 00:00:00 UTC
]
```

### 2. read_csv

Current behaviour:
```python
In [30]: pl.read_csv(io.StringIO('date\n2020-01-01T00:00:00+01:00'), try_parse_dates=True)
Out[30]:
shape: (1, 1)
┌───────────────────────────┐
│ date                      │
│ ---                       │
│ str                       │
╞═══════════════════════════╡
│ 2020-01-01T00:00:00+01:00 │
└───────────────────────────┘
```
Future behaviour:
```python
In [30]: pl.read_csv(io.StringIO('date\n2020-01-01T00:00:00+01:00'), try_parse_dates=True)
Out[30]:
shape: (1, 1)
┌─────────────────────────┐
│ date                    │
│ ---                     │
│ datetime[μs, UTC]       │
╞═════════════════════════╡
│ 2020-01-01 00:00:00 UTC │
└─────────────────────────┘
```

### 3. datatypes
Current behaviour:
```python
In [34]: pl.Series([datetime(2020, 1, 1)]).dt.replace_time_zone('+01:00')
Out[34]:
shape: (1,)
Series: '' [datetime[μs, +01:00]]
[
        2020-01-01 00:00:00 +01:00
]
```
Future behaviour: raise, advising to use one of the time zones in `chrono-tz` (e.g. `'Africa/Lagos'` / `'Europe/Brussels'`, etc....)

### 4. Constructors
Current:
```python
In [38]: pl.Series([datetime(2021, 1, 1, tzinfo=timezone(timedelta(hours=1)))])
Out[38]:
shape: (1,)
Series: '' [datetime[μs, +01:00]]
[
        2021-01-01 00:00:00 +01:00
]
```
Future:
```python
In [38]: pl.Series([datetime(2021, 1, 1, tzinfo=timezone(timedelta(hours=1)))])
Out[38]:
shape: (1,)
Series: '' [datetime[μs, UTC]]
[
        2020-12-31 23:00:00 UTC
]
```

### Any time

- [x] In `pl.read_csv`, parse offset-aware as `UTC` if `try_parse_dates=True` (they're currently just left as `utf8`, so this wouldn't really be breaking): https://github.com/pola-rs/polars/pull/8864

### Before  0.18

- [ ] warn if offset-aware format is passed and `utc` was set: https://github.com/pola-rs/polars/pull/8712
- [x] warn if Series contains time-zone-aware datetimes, warning that in the future the result will be of dtype `Datetime(time_unit, 'UTC')` https://github.com/pola-rs/polars/pull/8908
- [x] warn if fixed-offset is passed to `convert_time_zone`, `replace_time_zone`, `date_range`, or any other function with a `time_zone` argument (this will also end up warning for case 4 from above, as that uses `convert_time_zone`) #8924

### Breaking changes for 0.18

- [ ] remove `utc` argument, and convert offset-aware to UTC: https://github.com/pola-rs/polars/pull/8714
- [ ] remove parsing of fixed-offset time zones
- [ ] convert to UTC in constructors: `pl.Series([datetime(2021, 1, 1, tzinfo=timezone(timedelta(hours=1)))])` would convert to UTC: https://github.com/pola-rs/polars/pull/8881

## Related discussion

https://github.com/pola-rs/polars/issues/8289

## Notes

Just for clarification, parsing `'2020-01-01T00:00:00+01:00'` would still be allowed, but it would be converted to `pl.Datetime(time_unit, 'UTC')` instead of `pl.Datetime(time_unit, '+01:00')`. It's setting `'+01:00'` as the dtype of an entire column that would be disallowed.

**Comment by ritchie46** [comment]
Given that we still have to learn from this. Would it be better to have a 0.19 version in between? That would give us a bit more time to iron out the wrinkles.

**Comment by MarcoGorelli** [comment]
if there's something else you wanted to do for 0.19, then sure - don't think I'd suggest an extra minor version just for this

also, this change would bring a lot of simplification, so I think there's a lower chance of it introducing issues (if anything, it'll remove some, like the `pytest.mark.skip`'d test)
